spring.application.name=todo-app

spring.datasource.url=jdbc:postgresql://localhost:5432/todoapp
spring.datasource.username=eww
spring.datasource.password=eww
spring.jpa.hibernate.ddl-auto=create

# JWT
jwt.secret=3d7f4a2b9e1c6f8a0d5b2e7c4a9f1d6b3e8c5a2f7d4b1e9c6a3f0d7b4e2c9a1f
jwt.expiration=86400000

# enable to see security filter at work
# logging.level.org.springframework.security=TRACE

# api documentation
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=/swagger.html
