package org.example.todoapp;

import org.example.todoapp.dto.UserCreateRequest;
import org.example.todoapp.dto.UserResponse;
import org.example.todoapp.entity.MyUser;
import org.example.todoapp.entity.Role;
import org.example.todoapp.exception.EntityAlreadyExistsException;
import org.example.todoapp.exception.EntityNotFoundException;
import org.example.todoapp.repository.UserRepository;
import org.example.todoapp.service.UserService;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class UserServiceTests {

    @Mock
    private UserRepository userRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private UserService userService;

    @Nested
    class ReadAllTests{

        @Test
        void readAllOnEmptyRepository(){
            // arrange
            when(userRepository.findAll()).thenReturn(Collections.emptyList());

            // act
            List<UserResponse> users = userService.readAll();

            // assert
            assertTrue(users.isEmpty());
        }
    }

    @Nested
    class ReadTests{

        @Test
        void shouldReturnUserIfPresent(){
            // arrange
            MyUser user = new MyUser();
            // set id at runtime because id is autogenerated -> I don't want to expose it through a setter-method.
            ReflectionTestUtils.setField(user, "id", "someUUID");
            when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));

            // act
            UserResponse returnObject = userService.read(user.getId());

            // assert
            assertEquals(user.getId(), returnObject.id());
        }


        @Test
        void shouldThrowWhenUserNotFound(){
            // arrange
            MyUser user = new MyUser();
            ReflectionTestUtils.setField(user, "id", "someUUID");

            when(userRepository.findById(user.getId())).thenReturn(Optional.empty());

            // act & assert
            assertThrows(EntityNotFoundException.class, () -> userService.read(user.getId()));

        }
    }

    @Nested
    class CreateTests{

        @Test
        void shouldReturnNewUserOnSuccess(){
            // arrange
            UserCreateRequest request = new UserCreateRequest("username", "password");
            when(userRepository.findByUsername(request.username())).thenReturn(Optional.empty());
            when(passwordEncoder.encode("password")).thenReturn("hashed_password");
            MyUser savedUser = new MyUser();
            savedUser.setUsername(request.username());
            when(userRepository.save(ArgumentMatchers.any(MyUser.class))).thenReturn(savedUser);
            // act
            UserResponse response = userService.create(request);

            // assert
            assertEquals(request.username(), response.username());
        }

        @Test
        void shouldThrowIfUsernameAlreadyExists(){
            // arrange
            UserCreateRequest request = new UserCreateRequest("username", "password");
            when(userRepository.findByUsername(request.username())).thenReturn(Optional.of(new MyUser()));

            // act & assert
            assertThrows(EntityAlreadyExistsException.class, () -> userService.create(request));
        }
    }

    @Nested
    class DeleteTests{

        @Test
        void shouldThrowWhenUserNotFoundInDelete(){
            // arrange
            String id = "some_UUID";
            when(userRepository.findById(id)).thenReturn(Optional.empty());

            // act & assert
            assertThrows(EntityNotFoundException.class, () -> userService.delete(id));
        }

        @Test
        void shouldDeleteUserWhenFound(){
            // arrange
            MyUser user = new MyUser();
            ReflectionTestUtils.setField(user, "id", "some_UUID");
            when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));

            // act
            UserResponse response = userService.delete(user.getId());

            // assert
            assertEquals(response.id(), user.getId());
            verify(userRepository).delete(any());
        }

    }
}
