package org.example.todoapp;

import org.example.todoapp.dto.UserResponse;
import org.example.todoapp.entity.MyUser;
import org.example.todoapp.entity.Role;
import org.example.todoapp.exception.EntityNotFoundException;
import org.example.todoapp.repository.UserRepository;
import org.example.todoapp.service.UserService;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class UserServiceTests {

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private UserService userService;

    @Nested
    class ReadAllTests{

        @Test
        void readAllOnEmptyRepository(){
            // arrange
            when(userRepository.findAll()).thenReturn(Collections.emptyList());

            // act
            List<UserResponse> users = userService.readAll();

            // assert
            assertTrue(users.isEmpty());
        }
    }

    @Nested
    class ReadTests{

        @Test
        void shouldReturnUserIfPresent(){
            // arrange
            MyUser user = new MyUser();
            // set id at runtime because id is autogenerated -> I don't want to expose it through a setter-method.
            ReflectionTestUtils.setField(user, "id", "someUUID");
            when(userRepository.findById(user.getId())).thenReturn(Optional.of(user));

            // act
            UserResponse returnObject = userService.read(user.getId());

            // assert
            assertEquals(user.getId(), returnObject.id());
        }


        @Test
        void shouldThrowWhenUserNotFound(){
            // arrange
            MyUser user = new MyUser();
            ReflectionTestUtils.setField(user, "id", "someUUID");

            when(userRepository.findById(user.getId())).thenReturn(Optional.empty());

            // act & assert
            assertThrows(EntityNotFoundException.class, () -> userService.read(user.getId()));

        }
    }
}
