# ADR-001: Use ReflectionTestUtils to set automatically generated entity-IDs during testing

## Status
Accepted

## Context
Entities have autogenerated ids. To prevent manual change of these, they are not exposed through setters or a constructor.
During testing I need entities with known IDs.

## Decision
Use `ReflectionTestUtils.setField()` to set private `id` fields in tests.

I considered the following options
1) ReflectionTestUtils enabling overwrite of access modifiers during runtime.
2) Changing the entity with a package-private setter or constructor.

I decided on using ReflectionTestUtils because to me not changing production code seems cleaner and tradeoffs
are easily manageable for a single person.

## Consequences
- Production code does not have to be adapted to facilitate testing.
- Trade-off: Changing the field name in the entity is not refactor save and leads to runtime errors (and I can make typos in the field name without the compiler telling me).